project:
  type: book

lang: zh-CN
callout-appearance: simple

book:
  title: "基于 Quarto 的 LaTeX 工作流优化"
  author: "Strik0r"
  date: "10/27/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - project-initiation-and-structure.qmd
    - latex-related-settings.qmd
    - tikz-related-settings.qmd
    - publish.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    # include-in-header:
    #   text: |
    #     <script>
    #     window.MathJax = {
    #       tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
    #       chtml: { scale: 0.8 }  // 1.0 = 100%, adjust as you wish
    #     };
    #     </script>
    theme:
      cosmo
      brand
  pdf:
    documentclass: ctexbook
    pdf-engine: xelatex
    include-in-header:
      text: |
        \graphicspath{{tikzplots/png/}}

        \newif\ifaltgeometry   % 定义一个开关
        % \altgeometryfalse
        \altgeometrytrue

        \usepackage{xeCJK}
        \setCJKmainfont{Songti SC}
        \setCJKsansfont{Heiti SC}
        \setCJKmonofont{JetBrains Mono}
        \setmonofont{JetBrains Mono}
        \input{tex_utils/styles/documentsettings}
        \input{tex_utils/styles/titlesettings}



